### ISSUE TITLE
offset parameter is ignored in search endpoint

### ISSUE THREAD

**Issue by FluffyDiscord** [Saebasol/Heliotrope#271]
### Please explain the bug.

`offset` parameter is not working for `/search` endpoint as no matter the number, it always returns the first/most recent page

### How can I reproduce it?

```
curl -X 'POST' \
  'https://api.saebasol.org/api/hitomi/search' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "offset": 1,
  "query": [
    "female:loli"
  ]
}'
```
returns same `result` as 
```
curl -X 'POST' \
  'https://api.saebasol.org/api/hitomi/search' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "offset": 2,
  "query": [
    "female:loli"
  ]
}'
```

### Heliotrope version or Docker image version

```console
6.4.3 https://api.saebasol.org/docs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaidBySolo** [comment]
https://github.com/Saebasol/Heliotrope/blob/d99e7cd7152b9f1838b29394b3c4166abad20790/heliotrope/database/odm/__init__.py#L113



https://github.com/Saebasol/Heliotrope/blob/d99e7cd7152b9f1838b29394b3c4166abad20790/heliotrope/database/odm/__init__.py#L153

It seems to be a problem while working on #268.

Perhaps we forgot to pass the offset and limit arguments to the function because the function that creates the pipeline has default values.


We will fix this issue tomorrow, and if you are interested in this issue, you can open a PR.

**Comment by FluffyDiscord** [comment]
> https://github.com/Saebasol/Heliotrope/blob/d99e7cd7152b9f1838b29394b3c4166abad20790/heliotrope/database/odm/__init__.py#L113
> 
> https://github.com/Saebasol/Heliotrope/blob/d99e7cd7152b9f1838b29394b3c4166abad20790/heliotrope/database/odm/__init__.py#L153
> 
> It seems to be a problem while working on #268.
> 
> Perhaps we forgot to pass the offset and limit arguments to the function because the function that creates the pipeline has default values.
> 
> We will fix this issue tomorrow, and if you are interested in this issue, you can open a PR.

I see, PR created

**Comment by SaidBySolo** [comment]
Close in #272
